// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// StatusChecker is an autogenerated mock type for the StatusChecker type
type StatusChecker struct {
	mock.Mock
}

// Check provides a mock function with given fields: ctx, name
func (_m *StatusChecker) Check(ctx context.Context, name string) (string, error) {
	ret := _m.Called(ctx, name)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewStatusChecker interface {
	mock.TestingT
	Cleanup(func())
}

// NewStatusChecker creates a new instance of StatusChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStatusChecker(t mockConstructorTestingTNewStatusChecker) *StatusChecker {
	mock := &StatusChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
